[package]
name = "ffmpeg-owl-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
lazy_static = "1.5.0"
regex = "1.11.1"
rfd = "0.15.2"
tokio = { version = "1", features = ["full"] }